### ISSUE TITLE
Error: parsing UCSC GTF files

### ISSUE THREAD

**Issue by lcscs12345** [mills-lab/spectre#1]
[hg19.gtf.gz](https://github.com/mills-lab/spectre/files/72359/hg19.gtf.gz)
The script doesn't support GTF files downloaded using genePredToGTF (UCSC).

```
    $ python SPECtre.py --input accepted_hits.bam --fpkm isoforms.fpkm_tracking --log spectre_results.log --output spectre_results.txt --gtf hg19.gtf

    Traceback (most recent call last):
        File "SPECtre.py", line 1163, in <module>
          transcript_intervals = transcripts.interval_tree()
        File "SPECtre.py", line 187, in interval_tree
          gtf = self.anno()
        File "SPECtre.py", line 153, in anno
          gene_type = re.findall("gene_biotype .*;{1}", attributes)[0].split('"')[1]
    IndexError: list index out of range
```

**Comment by stonyc** [comment]
Support for non-Ensembl GTF will be added later. The current version only supports Ensembl GTF annotations from v78 release and later.

**Comment by stonyc** [comment]
Please refer to map_uscs_to_ensembl.py in the scripts/ directory. This script should provide temporary support for non-Ensembl GTFs. Native support for non-Ensembl GTF files will be added shortly.
