### ISSUE TITLE
Non-Ensembl GTF from non-model organism

### ISSUE THREAD

**Issue by ghost** [mills-lab/spectre#2]
Hi,

Spectre looks very interesting. In my case I am working on a non-model organism which has Transcriptome generated from de novo assembly usng "Trinity". I converted GFF3 file(obtained from "Transdecoder") to GTF file and used them in SPCTRE but it gave error saying

"Traceback (most recent call last):
  File "SPECtre.py", line 1049, in <module>
    transcript_intervals = transcripts.interval_tree()
  File "SPECtre.py", line 187, in interval_tree
    gtf = self.anno()
  File "SPECtre.py", line 153, in anno
    gene_type = re.findall("gene_biotype .*;{1}", attributes)[0].split('"')[1]
IndexError: list index out of range"

I know at present,SPECTRE supports only ENSEMBL gtf format, is there any way of converting gff3 or gtf file to enseml specific GTF format? Kindly guide me

**Comment by stonyc** [comment]
Support for non-Ensembl annotation formats will be added soon. What SPECtre looks for in the last column (the 'attribute' field) of a GTF is the expression "gene_biotype <label>". If you are able to add that label to your attribute fields, you should be able to coerce SPECtre to work. 

Refer to the following link for the general column format required by SPECtre:
http://www.ensembl.org/info/website/upload/gff.html

And the following link for biotypes:
http://www.gencodegenes.org/gencode_biotypes.html

**Comment by chiayic** [comment]
Hello,
Thank you for the tip. I'm also trying to use SPECtre and found this thread very helpful. I was reading the latest ver (released in Jan 2016) and noticed that the pattern for gene id was hard coded  ('gene_id "ENS[A-Z]_._";{1}', attributes) for those using non-Ensembl into consideration.
I ran into this different error,

```
Traceback (most recent call last):

  File "SPECtreAT.py", line 1327, in <module>
    transcript_metrics, reference_read_distribution = calculate_transcript_scores(transcript_gtf, transcript_fpkms, float(args.min), asite_buffers, psite_buffers, args.input, int(args.len), int(args.step), args.type, analyses, int(args.nt))
  File "SPECtreAT.py", line 914, in calculate_transcript_scores
    reference_distribution = calculate_reference_distribution(protein_coding_distributions)
  File "SPECtreAT.py", line 796, in calculate_reference_distribution
    reference_distribution[read_length] /= reference_transcripts
ZeroDivisionError: integer division or modulo by zero
```

From line 789 and 790:

```
reference_distribution = {26: 0, 27: 0, 28: 0, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0}
reference_transcripts = len(distributions)

```

Was the complaint due to the len(distributions) are all or partly zero? Not sure if it is related but my GTF contained only novel transcribed regions without CDS annotation. The 3rd columns are all designated as exon with the "processed_transcript" in the 9th column as 'gene_biotyp'.

Thank you for your time!

**Comment by Chudar-Arivu** [comment]
Hi,
 I tried by addng the gene_biotype into attribute column to coerce the spectre. But after adding the gene_biotype to the last column and ran the spectre, it gave me the following error

Traceback (most recent call last):
  File "SPECtre.py", line 1049, in <module>
    transcript_intervals = transcripts.interval_tree()
  File "SPECtre.py", line 187, in interval_tree
    gtf = self.anno()
  File "SPECtre.py", line 156, in anno
    gene, transcript = re.findall('ENS[A-Z]*G[0-9]*', attributes)[0], re.findall('ENS[A-Z]*T[0-9]*', attributes)[0]
IndexError: list index out of range

Now I dont know where the problem  lies.

**Comment by ghost** [comment]
Hi Chlayic and stonyc,

they recently updated the script with lot of changes and with lot comments and structured properly. Python users can easily understand the code. Try this script, you might probably get rid of your previous error and end up in new error like following

```
Traceback (most recent call last):
  File "SPECtre.py", line 1255, in <module>
    transcript_metrics, reference_read_distribution = calculate_transcript_scores(transcript_gtf, transcript_fpkms, float(args.min), asite_buffers, psite_buffers, args.input, int(args.len), int(args.step), args.type, analyses, int(args.nt))
  File "SPECtre.py", line 803, in calculate_transcript_scores
    transcripts, coordinates = zip(*flatten(gtf).iteritems())
ValueError: need more than 0 values to unpack
```

Like you said, I changed the hard coded "ENS[A-Z]....." with regular expressions to match my transcript names and ran the script. But it gave me the above error. 

My GTF file contained  gene, Transcript, UTR,CDS for every transcript and I included "protein_coding" in gene_biotype in 9th column for every transcript. 

How can I resolve this.

**Comment by chiayic** [comment]
Hi Chudar-Arivu,

I am still troubleshooting this error:

```
File "SPECtreAT.py", line 796, in calculate_reference_distribution
    reference_distribution[read_length] /= reference_transcripts
ZeroDivisionError: integer division or modulo by zero
```

I even downloaded the GTF from Ensembl (which is available for the organism I'm working on but my purpose is to use SPectre on novel genes) and still stuck at the same spot. My BAM files was not aligned to the GTF in the first place, so I was speculating if that could be the cause. My next move is to re-align the reads using Ensembl GTF and see how it goes.

I should probably mentioned that my test runs using test files that came with SPectre was successful without an issue.

**Comment by ghost** [comment]
Hi Chiayic,

Did you try with latest script which was updated just 17 hours ago.? If not try with latest script because I had the same error which you are having but when I ran with latest script it disappeared and gave me the above error. 

I too ran the test file and I obtained the output file but still I couldnt understand output because for protein coding transcripts, the FLOSS score and other scores were "NA" which appears strange. Anyhow keep me updated and I will let you know how it went for me.

**Comment by stonyc** [comment]
After being supplied the GTF used by the original poster, it was found that the GTF used was not formatted correctly. If other errors persist, please start another issue and I will address as presented. Thank you!
