### ISSUE TITLE
NAs in FLoss_Metric features

### ISSUE THREAD

**Issue by ghost** [mills-lab/spectre#3]
Hi,

In the test directory, there is a file called spectre_test.txt which I think is the output of spectre. When I opened that text file in excel I found "NA" for floss_metric_5UTR,FLOSS_metric_CDS and FLOSS_metric_3UTR. What does this "NA" for all entries in floss_metric features indicate?. Kindly guide me

**Comment by stonyc** [comment]
"NA" will occur for various metrics if certain coverage and/or transcript length requirements are not met.
