### ISSUE TITLE
test input error - input files format ..

### ISSUE THREAD

**Issue by tmargus** [mills-lab/spectre#5]
Hi,
Running SPECtre with test files gives an error message.
[ERROR]: Please check that your BAM, GTF and Cufflinks input files are formatted correctly...

command is following

python ./SPECtre.py --input test/test.bam --output test_result.txt  --log test_result.log  --fpkm test/isoforms-test.fpkm_tracking  --gtf test/Homo_sapiens.GRCh38.78.test.gtf 

Any ideas what is going on.
Cheers,
Tonu

**Comment by stonyc** [comment]
Hi Tonu,

There was an error with the function that checked chromosome formatting in the input files. If --target was not specified, it would throw the error you described. An optional check for the --target field has been added that should fix that problem. Please pull the latest version and verify that this fixes the error.

Thank you,
Tony

**Comment by tmargus** [comment]
Hi Tony,
It is working now.
Thanks!
T.

**Comment by stonyc** [comment]
Hi Tonu,
Great to hear, appreciate the feedback.
