### ISSUE TITLE
error in running spectre

### ISSUE THREAD

**Issue by PSSUN** [mills-lab/spectre#6]
I can run the example data successfully.
But when I change to my own data, here comes an error:

```
Traceback (most recent call last):
  File "./spectre-master/SPECtre.py", line 1327, in <module>
    transcript_metrics, reference_read_distribution = calculate_transcript_scores(transcript_gtf, transcript_fpkms, float(args.min), asite_buffers, psite_buffers, orfscore_buffers, args.input, int(args.len), int(args.step), args.type, analyses, offsets, target_chroms, int(args.nt))
  File "./spectre-master/SPECtre.py", line 840, in calculate_transcript_scores
    transcripts, intervals = zip(*flatten(gtf).iteritems())
ValueError: need more than 0 values to unpack
```
command is:
`python ./spectre-master/SPECtre.py --input ./tophat_out/accepted_hits.bam --output result.txt --gtf /home/sun/sps/tair10.gff3 --fpkm ./isoforms.fpkm_tracking`

Is there something wrong with my data? What can I do to solve this problem?

**Comment by stonyc** [comment]
Hello, this error is typically encountered when the input references are not matched (hg19 for BAM, Ensembl for GTF) or if there are reference regions included in one of the inputs that are not present in the others. For the first scenario, there may be a problem if one reference annotation denotes chromosomes as "chr1" versus simply "1". For the second scenario, Ensembl reference annotations may include many non-chromosomal contigs. If these contigs are not in the BAM or Cufflinks input, then that may cause this error. I would suggest two possible solutions:

1) Check that all of your reference inputs are the same (for example, hg38 for BAM, GTF, and Cufflinks),
2) If the reference versions are all the same from step 1, then make sure that all of the regions in your input files are present. You can ensure this by using the same GTF for alignment, cufflinks, and SPECtre. Alternatively, you might consider filtering your GTF to only the canonical set of chromosomal regions depending on your organism, cell line, etc.

I can provide additional assistance depending on the results of those proposed solutions.

**Comment by PSSUN** [comment]
Thank you for your derailed answer.The program run successfully.
By the way ,the dog is lovely.
